# Autogenerated from a Treetop grammar. Edits may be lost.


module Ennio
    module Scheme
      include Treetop::Runtime

      def root
        @root ||= :program
      end

      def _nt_program
        start_index = index
        if node_cache[:program].has_key?(index)
          cached = node_cache[:program][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        s0, i0 = [], index
        loop do
          r1 = _nt_s_expression
          if r1
            s0 << r1
          else
            break
          end
        end
        if s0.empty?
          @index = i0
          r0 = nil
        else
          r0 = instantiate_node(Program,input, i0...index, s0)
        end

        node_cache[:program][start_index] = r0

        r0
      end

      def _nt_l_paren
        start_index = index
        if node_cache[:l_paren].has_key?(index)
          cached = node_cache[:l_paren][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        if has_terminal?('(', false, index)
          r0 = instantiate_node(LParen,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure('(')
          r0 = nil
        end

        node_cache[:l_paren][start_index] = r0

        r0
      end

      def _nt_r_paren
        start_index = index
        if node_cache[:r_paren].has_key?(index)
          cached = node_cache[:r_paren][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        if has_terminal?(')', false, index)
          r0 = instantiate_node(RParen,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure(')')
          r0 = nil
        end

        node_cache[:r_paren][start_index] = r0

        r0
      end

      module SExpression0
        def value
          elements[0]
        end

      end

      module SExpression1
        def operator
          elements[0]
        end

      end

      module SExpression2
        def l_paren
          elements[1]
        end

        def r_paren
          elements[5]
        end

      end

      def _nt_s_expression
        start_index = index
        if node_cache[:s_expression].has_key?(index)
          cached = node_cache[:s_expression][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0, s0 = index, []
        s1, i1 = [], index
        loop do
          r2 = _nt_space
          if r2
            s1 << r2
          else
            break
          end
        end
        r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
        s0 << r1
        if r1
          r3 = _nt_l_paren
          s0 << r3
          if r3
            s4, i4 = [], index
            loop do
              r5 = _nt_space
              if r5
                s4 << r5
              else
                break
              end
            end
            r4 = instantiate_node(SyntaxNode,input, i4...index, s4)
            s0 << r4
            if r4
              i6, s6 = index, []
              r7 = _nt_operator
              s6 << r7
              if r7
                s8, i8 = [], index
                loop do
                  r9 = _nt_space
                  if r9
                    s8 << r9
                  else
                    break
                  end
                end
                r8 = instantiate_node(SyntaxNode,input, i8...index, s8)
                s6 << r8
                if r8
                  s10, i10 = [], index
                  loop do
                    i11, s11 = index, []
                    r12 = _nt_value
                    s11 << r12
                    if r12
                      s13, i13 = [], index
                      loop do
                        r14 = _nt_space
                        if r14
                          s13 << r14
                        else
                          break
                        end
                      end
                      r13 = instantiate_node(SyntaxNode,input, i13...index, s13)
                      s11 << r13
                    end
                    if s11.last
                      r11 = instantiate_node(SyntaxNode,input, i11...index, s11)
                      r11.extend(SExpression0)
                    else
                      @index = i11
                      r11 = nil
                    end
                    if r11
                      s10 << r11
                    else
                      break
                    end
                  end
                  r10 = instantiate_node(SyntaxNode,input, i10...index, s10)
                  s6 << r10
                end
              end
              if s6.last
                r6 = instantiate_node(SyntaxNode,input, i6...index, s6)
                r6.extend(SExpression1)
              else
                @index = i6
                r6 = nil
              end
              s0 << r6
              if r6
                s15, i15 = [], index
                loop do
                  r16 = _nt_space
                  if r16
                    s15 << r16
                  else
                    break
                  end
                end
                r15 = instantiate_node(SyntaxNode,input, i15...index, s15)
                s0 << r15
                if r15
                  r17 = _nt_r_paren
                  s0 << r17
                  if r17
                    s18, i18 = [], index
                    loop do
                      r19 = _nt_space
                      if r19
                        s18 << r19
                      else
                        break
                      end
                    end
                    r18 = instantiate_node(SyntaxNode,input, i18...index, s18)
                    s0 << r18
                  end
                end
              end
            end
          end
        end
        if s0.last
          r0 = instantiate_node(SExpression,input, i0...index, s0)
          r0.extend(SExpression2)
        else
          @index = i0
          r0 = nil
        end

        node_cache[:s_expression][start_index] = r0

        r0
      end

      def _nt_operator
        start_index = index
        if node_cache[:operator].has_key?(index)
          cached = node_cache[:operator][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0 = index
        r1 = _nt_arithmetic_operator
        if r1
          r0 = r1
          r0.extend(Operator)
        else
          r2 = _nt_relational_operator
          if r2
            r0 = r2
            r0.extend(Operator)
          else
            r3 = _nt_logical_operator
            if r3
              r0 = r3
              r0.extend(Operator)
            else
              r4 = _nt_dynamic_word
              if r4
                r0 = r4
                r0.extend(Operator)
              else
                @index = i0
                r0 = nil
              end
            end
          end
        end

        node_cache[:operator][start_index] = r0

        r0
      end

      def _nt_arithmetic_operator
        start_index = index
        if node_cache[:arithmetic_operator].has_key?(index)
          cached = node_cache[:arithmetic_operator][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0 = index
        if has_terminal?("+", false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure("+")
          r1 = nil
        end
        if r1
          r0 = r1
          r0.extend(ArithmeticOperator)
        else
          if has_terminal?("-", false, index)
            r2 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure("-")
            r2 = nil
          end
          if r2
            r0 = r2
            r0.extend(ArithmeticOperator)
          else
            if has_terminal?("*", false, index)
              r3 = instantiate_node(SyntaxNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure("*")
              r3 = nil
            end
            if r3
              r0 = r3
              r0.extend(ArithmeticOperator)
            else
              if has_terminal?("/", false, index)
                r4 = instantiate_node(SyntaxNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure("/")
                r4 = nil
              end
              if r4
                r0 = r4
                r0.extend(ArithmeticOperator)
              else
                if has_terminal?("%", false, index)
                  r5 = instantiate_node(SyntaxNode,input, index...(index + 1))
                  @index += 1
                else
                  terminal_parse_failure("%")
                  r5 = nil
                end
                if r5
                  r0 = r5
                  r0.extend(ArithmeticOperator)
                else
                  @index = i0
                  r0 = nil
                end
              end
            end
          end
        end

        node_cache[:arithmetic_operator][start_index] = r0

        r0
      end

      def _nt_relational_operator
        start_index = index
        if node_cache[:relational_operator].has_key?(index)
          cached = node_cache[:relational_operator][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0 = index
        if has_terminal?("=", false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure("=")
          r1 = nil
        end
        if r1
          r0 = r1
          r0.extend(RelationalOperator)
        else
          if has_terminal?("=!", false, index)
            r2 = instantiate_node(SyntaxNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure("=!")
            r2 = nil
          end
          if r2
            r0 = r2
            r0.extend(RelationalOperator)
          else
            if has_terminal?("<", false, index)
              r3 = instantiate_node(SyntaxNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure("<")
              r3 = nil
            end
            if r3
              r0 = r3
              r0.extend(RelationalOperator)
            else
              if has_terminal?(">", false, index)
                r4 = instantiate_node(SyntaxNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure(">")
                r4 = nil
              end
              if r4
                r0 = r4
                r0.extend(RelationalOperator)
              else
                if has_terminal?("<=", false, index)
                  r5 = instantiate_node(SyntaxNode,input, index...(index + 2))
                  @index += 2
                else
                  terminal_parse_failure("<=")
                  r5 = nil
                end
                if r5
                  r0 = r5
                  r0.extend(RelationalOperator)
                else
                  if has_terminal?(">=", false, index)
                    r6 = instantiate_node(SyntaxNode,input, index...(index + 2))
                    @index += 2
                  else
                    terminal_parse_failure(">=")
                    r6 = nil
                  end
                  if r6
                    r0 = r6
                    r0.extend(RelationalOperator)
                  else
                    @index = i0
                    r0 = nil
                  end
                end
              end
            end
          end
        end

        node_cache[:relational_operator][start_index] = r0

        r0
      end

      def _nt_logical_operator
        start_index = index
        if node_cache[:logical_operator].has_key?(index)
          cached = node_cache[:logical_operator][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0 = index
        if has_terminal?("and", false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 3))
          @index += 3
        else
          terminal_parse_failure("and")
          r1 = nil
        end
        if r1
          r0 = r1
          r0.extend(LogicalOperator)
        else
          if has_terminal?("or", false, index)
            r2 = instantiate_node(SyntaxNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure("or")
            r2 = nil
          end
          if r2
            r0 = r2
            r0.extend(LogicalOperator)
          else
            if has_terminal?("not", false, index)
              r3 = instantiate_node(SyntaxNode,input, index...(index + 3))
              @index += 3
            else
              terminal_parse_failure("not")
              r3 = nil
            end
            if r3
              r0 = r3
              r0.extend(LogicalOperator)
            else
              @index = i0
              r0 = nil
            end
          end
        end

        node_cache[:logical_operator][start_index] = r0

        r0
      end

      def _nt_dynamic_word
        start_index = index
        if node_cache[:dynamic_word].has_key?(index)
          cached = node_cache[:dynamic_word][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        s0, i0 = [], index
        loop do
          if has_terminal?('\G[a-z]', true, index)
            r1 = true
            @index += 1
          else
            r1 = nil
          end
          if r1
            s0 << r1
          else
            break
          end
        end
        if s0.empty?
          @index = i0
          r0 = nil
        else
          r0 = instantiate_node(DynamicWord,input, i0...index, s0)
        end

        node_cache[:dynamic_word][start_index] = r0

        r0
      end

      def _nt_value
        start_index = index
        if node_cache[:value].has_key?(index)
          cached = node_cache[:value][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0 = index
        r1 = _nt_integer
        if r1
          r0 = r1
          r0.extend(Value)
        else
          r2 = _nt_float
          if r2
            r0 = r2
            r0.extend(Value)
          else
            r3 = _nt_boolean
            if r3
              r0 = r3
              r0.extend(Value)
            else
              r4 = _nt_single_quoted_string
              if r4
                r0 = r4
                r0.extend(Value)
              else
                r5 = _nt_double_quoted_string
                if r5
                  r0 = r5
                  r0.extend(Value)
                else
                  r6 = _nt_nil_value
                  if r6
                    r0 = r6
                    r0.extend(Value)
                  else
                    r7 = _nt_dynamic_word
                    if r7
                      r0 = r7
                      r0.extend(Value)
                    else
                      r8 = _nt_s_expression
                      if r8
                        r0 = r8
                        r0.extend(Value)
                      else
                        @index = i0
                        r0 = nil
                      end
                    end
                  end
                end
              end
            end
          end
        end

        node_cache[:value][start_index] = r0

        r0
      end

      def _nt_nil_value
        start_index = index
        if node_cache[:nil_value].has_key?(index)
          cached = node_cache[:nil_value][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        if has_terminal?("nil", false, index)
          r0 = instantiate_node(NilNode,input, index...(index + 3))
          @index += 3
        else
          terminal_parse_failure("nil")
          r0 = nil
        end

        node_cache[:nil_value][start_index] = r0

        r0
      end

      module List0
        def value
          elements[0]
        end

      end

      module List1
      end

      def _nt_list
        start_index = index
        if node_cache[:list].has_key?(index)
          cached = node_cache[:list][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0, s0 = index, []
        if has_terminal?("'", false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure("'")
          r1 = nil
        end
        s0 << r1
        if r1
          s2, i2 = [], index
          loop do
            r3 = _nt_space
            if r3
              s2 << r3
            else
              break
            end
          end
          r2 = instantiate_node(SyntaxNode,input, i2...index, s2)
          s0 << r2
          if r2
            if has_terminal?('(', false, index)
              r4 = instantiate_node(SyntaxNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure('(')
              r4 = nil
            end
            s0 << r4
            if r4
              i5, s5 = index, []
              r6 = _nt_value
              s5 << r6
              if r6
                s7, i7 = [], index
                loop do
                  r8 = _nt_space
                  if r8
                    s7 << r8
                  else
                    break
                  end
                end
                r7 = instantiate_node(SyntaxNode,input, i7...index, s7)
                s5 << r7
              end
              if s5.last
                r5 = instantiate_node(SyntaxNode,input, i5...index, s5)
                r5.extend(List0)
              else
                @index = i5
                r5 = nil
              end
              s0 << r5
              if r5
                if has_terminal?(')', false, index)
                  r9 = instantiate_node(SyntaxNode,input, index...(index + 1))
                  @index += 1
                else
                  terminal_parse_failure(')')
                  r9 = nil
                end
                s0 << r9
              end
            end
          end
        end
        if s0.last
          r0 = instantiate_node(List,input, i0...index, s0)
          r0.extend(List1)
        else
          @index = i0
          r0 = nil
        end

        node_cache[:list][start_index] = r0

        r0
      end

      def _nt_integer
        start_index = index
        if node_cache[:integer].has_key?(index)
          cached = node_cache[:integer][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        s0, i0 = [], index
        loop do
          if has_terminal?('\G[0-9]', true, index)
            r1 = true
            @index += 1
          else
            r1 = nil
          end
          if r1
            s0 << r1
          else
            break
          end
        end
        if s0.empty?
          @index = i0
          r0 = nil
        else
          r0 = instantiate_node(IntegerNode,input, i0...index, s0)
        end

        node_cache[:integer][start_index] = r0

        r0
      end

      module Float0
      end

      def _nt_float
        start_index = index
        if node_cache[:float].has_key?(index)
          cached = node_cache[:float][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0, s0 = index, []
        s1, i1 = [], index
        loop do
          if has_terminal?('\G[0-9]', true, index)
            r2 = true
            @index += 1
          else
            r2 = nil
          end
          if r2
            s1 << r2
          else
            break
          end
        end
        r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
        s0 << r1
        if r1
          if has_terminal?(".", false, index)
            r3 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure(".")
            r3 = nil
          end
          s0 << r3
          if r3
            s4, i4 = [], index
            loop do
              if has_terminal?('\G[0-9]', true, index)
                r5 = true
                @index += 1
              else
                r5 = nil
              end
              if r5
                s4 << r5
              else
                break
              end
            end
            if s4.empty?
              @index = i4
              r4 = nil
            else
              r4 = instantiate_node(SyntaxNode,input, i4...index, s4)
            end
            s0 << r4
          end
        end
        if s0.last
          r0 = instantiate_node(FloatNode,input, i0...index, s0)
          r0.extend(Float0)
        else
          @index = i0
          r0 = nil
        end

        node_cache[:float][start_index] = r0

        r0
      end

      def _nt_boolean
        start_index = index
        if node_cache[:boolean].has_key?(index)
          cached = node_cache[:boolean][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0 = index
        if has_terminal?("#t", false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 2))
          @index += 2
        else
          terminal_parse_failure("#t")
          r1 = nil
        end
        if r1
          r0 = r1
          r0.extend(BooleanNode)
        else
          if has_terminal?("#f", false, index)
            r2 = instantiate_node(SyntaxNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure("#f")
            r2 = nil
          end
          if r2
            r0 = r2
            r0.extend(BooleanNode)
          else
            @index = i0
            r0 = nil
          end
        end

        node_cache[:boolean][start_index] = r0

        r0
      end

      def _nt_space
        start_index = index
        if node_cache[:space].has_key?(index)
          cached = node_cache[:space][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        if has_terminal?('\G[\\s\\n\\r\\t]', true, index)
          r0 = instantiate_node(Space,input, index...(index + 1))
          @index += 1
        else
          r0 = nil
        end

        node_cache[:space][start_index] = r0

        r0
      end

      module DoubleQuotedString0
      end

      def _nt_double_quoted_string
        start_index = index
        if node_cache[:double_quoted_string].has_key?(index)
          cached = node_cache[:double_quoted_string][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0, s0 = index, []
        if has_terminal?('"', false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure('"')
          r1 = nil
        end
        s0 << r1
        if r1
          s2, i2 = [], index
          loop do
            i3 = index
            if has_terminal?('\\"', false, index)
              r4 = instantiate_node(SyntaxNode,input, index...(index + 2))
              @index += 2
            else
              terminal_parse_failure('\\"')
              r4 = nil
            end
            if r4
              r3 = r4
            else
              if has_terminal?('\G[^"]', true, index)
                r5 = true
                @index += 1
              else
                r5 = nil
              end
              if r5
                r3 = r5
              else
                @index = i3
                r3 = nil
              end
            end
            if r3
              s2 << r3
            else
              break
            end
          end
          r2 = instantiate_node(SyntaxNode,input, i2...index, s2)
          s0 << r2
          if r2
            if has_terminal?('"', false, index)
              r6 = instantiate_node(SyntaxNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure('"')
              r6 = nil
            end
            s0 << r6
          end
        end
        if s0.last
          r0 = instantiate_node(DoubleQuotedString,input, i0...index, s0)
          r0.extend(DoubleQuotedString0)
        else
          @index = i0
          r0 = nil
        end

        node_cache[:double_quoted_string][start_index] = r0

        r0
      end

      module SingleQuotedString0
      end

      def _nt_single_quoted_string
        start_index = index
        if node_cache[:single_quoted_string].has_key?(index)
          cached = node_cache[:single_quoted_string][index]
          if cached
            cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
            @index = cached.interval.end
          end
          return cached
        end

        i0, s0 = index, []
        if has_terminal?("'", false, index)
          r1 = instantiate_node(SyntaxNode,input, index...(index + 1))
          @index += 1
        else
          terminal_parse_failure("'")
          r1 = nil
        end
        s0 << r1
        if r1
          s2, i2 = [], index
          loop do
            i3 = index
            if has_terminal?("\\'", false, index)
              r4 = instantiate_node(SyntaxNode,input, index...(index + 2))
              @index += 2
            else
              terminal_parse_failure("\\'")
              r4 = nil
            end
            if r4
              r3 = r4
            else
              if has_terminal?('\G[^\']', true, index)
                r5 = true
                @index += 1
              else
                r5 = nil
              end
              if r5
                r3 = r5
              else
                @index = i3
                r3 = nil
              end
            end
            if r3
              s2 << r3
            else
              break
            end
          end
          r2 = instantiate_node(SyntaxNode,input, i2...index, s2)
          s0 << r2
          if r2
            if has_terminal?("'", false, index)
              r6 = instantiate_node(SyntaxNode,input, index...(index + 1))
              @index += 1
            else
              terminal_parse_failure("'")
              r6 = nil
            end
            s0 << r6
          end
        end
        if s0.last
          r0 = instantiate_node(SingleQuotedString,input, i0...index, s0)
          r0.extend(SingleQuotedString0)
        else
          @index = i0
          r0 = nil
        end

        node_cache[:single_quoted_string][start_index] = r0

        r0
      end

    end

    class SchemeParser < Treetop::Runtime::CompiledParser
      include Scheme
    end

end
